# TRAVIS CI configuration
#   using Cabal for resolving dependencies
#   see also  https://github.com/hvr/multi-ghc-travis
#
#   This script is inspired by Michael Snoyman's
#     https://docs.haskellstack.org/en/stable/GUIDE/#travis-with-caching

# I do not wish to receive email notifications
notifications:
  email: false

# request container-based infracstructure (needed for caching)
sudo: false

# choose a lightweight base image; we provide our own build tools.
language: c

# caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

# build matrix
matrix:
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: { apt: { packages: [cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc] } }
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: { apt: { packages: [cabal-install-1.22, ghc-7.10.1], sources: [hvr-ghc] } }
    - env: CABALVER=1.24 GHCVER=8.0.1
      addons: { apt: { packages: [cabal-install-1.24, ghc-8.0.1], sources: [hvr-ghc] } }

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - export PACKAGES="hyper/ hyper-haskell-server/ hyper-extra/"

install:
  - cabal --version
  - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
# we only try test the Haskell bits of the project
  - cd haskell/
  - cabal install --only-dependencies $PACKAGES

script:
- |
  set -ex
  ORIGDIR=$(pwd)
  for dir in $PACKAGES
  do
    cd $dir
    cabal check || [ "$CABALVER" == "1.16" ] || exit 1
    cabal sdist
    PKGVER=$(cabal info . | awk '{print $2;exit}')
    SRC_TGZ=$PKGVER.tar.gz
    cd dist
    tar zxfv "$SRC_TGZ"
    cd "$PKGVER"
    (cabal configure --enable-tests && cabal build && cabal test && cabal install --force-reinstalls) || exit 1
    cd $ORIGDIR
  done
  set +ex
